### PR TITLE
Add native support for loading local images.

### PR DESCRIPTION
**Pull request by thanhzusu**
Due to #45, I created the PR for the fixing.

### CODE REVIEW

**Comment by thanhzusu** [comment]
@DylanVann please take your time to check this issue.

**Comment by 1c7** [comment]
Hi @DylanVann  can you review this PR?
Thanks for building `react-native-fast-image` but it seem like it doesn't support local image at this point. 
I really need display local image 

:D

**Comment by 1c7** [comment]
I am using `react-native-image-crop-picker`to select multiple image 
then use FlatList to display them. 

`<Image>` can take up to 450MB memory if I select 50 image.
(image size from 80kB to 700kb to little over 1MB)

I am hoping FastImage can reduce some memory

**Comment by jpkrause** [comment]
@DylanVann any chance you want to merge this (or add this feature yourself)? It would be very useful.

**Comment by JakeRawr** [comment]
@DylanVann +1, this PR would help a lot

**Comment by DylanVann** [comment]
Originally there was no intention of supporting local images. It does seem though that people want a complete `Image` replacement that they can use anywhere they can use `Image`. Some people even think we should merge this into core as a replacement for `Image`.

This is all to say that I'm going to look into merging this, sorry it's taken so long.

**Comment by DylanVann** [comment]
Thanks for figuring this our @thanhzusu, sorry it's taken so long to get to. Because of conflicts with the Glide update I had to change the way this is done a bit. I did reference this PR and I'll credit you in the release notes though, thanks!

**Pull request closed without merging**
