### PR TITLE
Fix Source's Cache type

### PR DESCRIPTION
**Pull request by kulyk**
`Cache` property type was equal to `Priority` (with `low | normal | high` values)
However, `FastImage.cacheControl` contains `immutable`, `web` and `cacheOnly` values, so the types are not matching

Fixed by changing `Cache` type to `'immutable' | 'web' | 'cacheOnly'`

### CODE REVIEW

**Comment by radko93** [comment]
@DylanVann this is minor but will help a lot!

**Comment by krisztiaan-uic** [comment]
#676 is the same but with derived typing from the declared const

**Comment by krisztiaan-uic** [comment]
@kulyk would you mind merging #676 into yours, so I could close that one?
also, anyone can just make these changes locally, and use `patch-package` to apply it in your current project until this one is merged

**Comment by kulyk** [comment]
@krisztiaan-uic sure, thanks a lot! I'll do it on weekends and post and update here

**Comment by kulyk** [comment]
Hi @krisztiaan-uic  I've merged #676 code into this branch, so now `Priority` and `Cache` types are derived from const values and exported. Thank you for your work!

However, all the recent CI checks fail due to Node v13 breaking change. I'll open a new PR to fix the CI checks a bit later

**Comment by kulyk** [comment]
CircleCI fix is ready at #683 
@DylanVann hi, please take a look 🙏

**Comment by DylanVann** [comment]
Hi @kulyk, thanks for the PR!

I merged the other one to fix the Cache type. I think it would be better to just use string unions rather than exporting enum like objects, then this issue won't end up reoccurring.

**Comment by kulyk** [comment]
Hi @DylanVann,

The best thing is to have a new release :) Thank you for your time!

**Pull request closed without merging**
