### PR TITLE
Fixes crash where activity was already destroyed

### PR DESCRIPTION
**Pull request by patrickkempff**
We saw some strange crashes in our brownfield app. We use a recycle list view with react-native-fast-image powered thumbnails. When the user navigates quickly to a new page and presses the back button really quick the app crashes with the following error:

```
Fatal Exception: java.lang.RuntimeException
java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
```
One of the threads in the glide repro: https://github.com/bumptech/glide/issues/1484

This PR basically adds some guards to the fast-image implementation. We have tested this in production (an app with over 2 million downloads and thousands of new users per day) without crashes. We did not notice any side effects.

**EDIT: i have pushed an new PR based on this one, that fixes the handling of uri's from require() on Android production builds, see #283**

### CODE REVIEW

**Comment by n1ru4l** [comment]
@DylanVann can we get this changes into master and released as a new version asap?

This will solve the longstanding issue: https://github.com/DylanVann/react-native-fast-image/issues/245

@patrickkempff Thank you for your work!

**Comment by anhtuank7c** [comment]
Cc @DylanVann

**Comment by linguokun1** [comment]
Thannks @patrickkempff Thanks @DylanVann.Expecting new release

**Comment by linguokun1** [comment]
Thanks @patrickkempff 
Thanks @DylanVann 
Expecting new release.

**Comment by linguokun1** [comment]
Hi @DylanVann
Please remember to do a release, I really need it because our Company's app will release next few day and now is at internal testing.

**Pull request merged**
