### PR TITLE
Added null check on  getCurrentActivity()'s return value

### PR DESCRIPTION
**Pull request by Kouznetsov**
We noticed a lot of crashes because of getCurrentActivity() returning null. This PR contains a simple null check to avoid crashing.

### CODE REVIEW

**Comment by LuigiQuarta** [comment]
I've encountered the same problem on my project and this fix resolve it. Thank you.

**Comment by ifsnow** [comment]
@DylanVann Are you planning to merge this PR. I'm sure this crash is occurring. I hope this problem is resolved.

**Comment by Kouznetsov** [comment]
Meanwhile, I made a fork with the fix applied. https://github.com/Kouznetsov/kh-rn-fast-image

**Comment by DylanVann** [comment]
Looks reasonable. I guess in this case the preloading just won't work though. That's unfortunate, better not to crash though.

**Comment by DylanVann** [comment]
Thanks @Kouznetsov

**Pull request merged**
