### PR TITLE
Add blurRadius property.

### PR DESCRIPTION
**Pull request by sroze**
This is what I've done so far to add the `blurRadius` capabilities to FastImage. I probably will not go forward but if anybody wants to continue, it would be fantastic.

### CODE REVIEW

**Comment by DylanVann** [comment]
This is cool. I'd really like to have support for `blurRadius`. I'd want to have it be cross platform before merging it in though.

**Comment by n1ru4l** [comment]
Would also be awesome if we could use blurRadius with local images.

**Comment by DylanVann** [comment]
It would also be nice if it worked better than `Image`'s `blurRadius`.

It looks different in development vs. production.
It looks different on iOS vs. Android.

**Comment by RageOfJustice** [comment]
Hello! Any updates?

**Comment by sroze** [comment]
I won't have time to invest in this in the upcoming months. Contributions welcome (I can add contributors to my fork; or you can PR on it, I'll merge) :)

**Comment by l1br3** [comment]
This does not working as expected, I feel that every time I load the image from cache, another blur get applied. After few unmounting/mounting, I get a monochrom: an image of a single color. And of course, huge performance issue because of the huge amount of transformations I guess.

I don't really know where does it comes from...

I also gave a look at Glide and it seems more complicated than the iOS library to integrate blur.

**Comment by phuongwd** [comment]
Hello! Any updates?

**Comment by sroze** [comment]
> Contributions welcome

🙂

**Comment by DylanVann** [comment]
I'd like to implement this but I'm not going to merge single platform features so we need to figure out blur on Android first.

**Comment by nica0012** [comment]
How is this coming along fellas?

**Comment by DylanVann** [comment]
I like this implementation, I am closing this PR to clean up open PRs though. Note saved here: https://github.com/DylanVann/react-native-fast-image/issues/50#issuecomment-541496613

**Comment by danleveille** [comment]
Could this be implemented as iOS only, with a note in documentation that it's iOS? It might encourage more Android developers to contribute.

**Pull request closed without merging**
