### PR TITLE
Fix memory leaks and add support border radius on android

### PR DESCRIPTION
**Pull request by chaitanya0bhagvan**
The Android implementation makes use of static variables that were causing memory leaks. Code refactor and use of WeakHashMap has the fixed memory leak due to this library.

Add support for border-radius on Android.

### CODE REVIEW

**Comment by chaitanya0bhagvan** [comment]
@DylanVann Can you check whether this can be merged? I am using react-native-navigation and I notice memory leaks emanating from this library.

**Comment by clarksandholtz** [comment]
@DylanVann is there an ETA on this merge?

**Comment by BeckZero** [comment]
dont work 

..\node_modules\react-native-fast-image\android\src\main\java\com\dylanvann\fastimage\FastImageViewManager.java:8: error: cannot find symbol

import android.support.v7.widget.AppCompatImageView;

**Comment by chaitanya0bhagvan** [comment]
@BeckZero Apologies for not replying sooner. I assumed that everyone would be using the latest versions of Android support libraries. I made the necessary changes. Please try and let me know.

**Comment by DylanVann** [comment]
Thank you 🥇 . I will look into the memory issue.

The border radius issue can be discussed here: https://github.com/DylanVann/react-native-fast-image/pull/59#issuecomment-361796662

**Comment by chaitanya0bhagvan** [comment]
@DylanVann @clarksandholtz @BeckZero With the latest commit borderRadius can be applied to the image with a normal style object. It also supports borderRadius for individual corners eg. borderTopLeftRadius etc

**Comment by fangasvsass** [comment]
add the Radius code , it will be out of memory 
    compile 'com.github.bumptech.glide:annotations:4.4.0'
    compile 'jp.wasabeef:glide-transformations:3.1.0'
//        if (YogaConstants.UNDEFINED != view.borderRadius) {
//            options = options.apply(bitmapTransform(new BlurTransformation((int) view.borderRadius)));
//        }
//        if (view.borderCornerRadii != null) {
//        List<Transformation> transformations = new ArrayList<>()
//            MultiTransformation multi;
//            RoundedCornersTransformation.CornerType cornerType;
//            for (int i = 0; i < view.borderCornerRadii.length; i++) {
//                if (YogaConstants.UNDEFINED != view.borderCornerRadii[i]) {
//                    continue;
//                }
//                cornerType = CORNER_TYPES[i];
//                transformations.add(new RoundedCornersTransformation((int) view.borderCornerRadii[i], 0,
//                        cornerType));
//            }
//            multi = new MultiTransformation(transformations);
//            options = options.apply(bitmapTransform(multi));
//
//        }

**Comment by chaitanya0bhagvan** [comment]
@fangasvsass Can you elaborate?

**Comment by fangasvsass** [comment]
@Override
    protected void onAfterUpdateTransaction(ImageViewWithUrl view) {
        super.onAfterUpdateTransaction(view);
        String key = view.glideUrl.toStringUrl();
        OkHttpProgressGlideModule.expect(key, this);
        List<ImageViewWithUrl> viewsForKey = VIEWS_FOR_URLS.get(key);
        if (viewsForKey != null && !viewsForKey.contains(view)) {
            viewsForKey.add(view);
        } else if (viewsForKey == null) {
            List<ImageViewWithUrl> newViewsForKeys = new ArrayList(Arrays.asList(view));
            VIEWS_FOR_URLS.put(key, newViewsForKeys);
        }
//
        ThemedReactContext context = (ThemedReactContext) view.getContext();
        RCTEventEmitter eventEmitter = context.getJSModule(RCTEventEmitter.class);
        int viewId = view.getId();
        eventEmitter.receiveEvent(viewId, REACT_ON_LOAD_START_EVENT, new WritableNativeMap());
        RequestOptions options = new RequestOptions()
                .priority(view.priority)
                .placeholder(TRANSPARENT_DRAWABLE);

        if (view.circle) {
            RequestOptions op = RequestOptions.circleCropTransform();
            options = options.apply(op);
        }
//        if (YogaConstants.UNDEFINED != view.borderRadius) {
//            options = options.apply(bitmapTransform(new BlurTransformation((int) view.borderRadius)));
//        }
//        if (view.borderCornerRadii != null) {
//        List<Transformation> transformations = new ArrayList<>()
//            MultiTransformation multi;
//            RoundedCornersTransformation.CornerType cornerType;
//            for (int i = 0; i < view.borderCornerRadii.length; i++) {
//                if (YogaConstants.UNDEFINED != view.borderCornerRadii[i]) {
//                    continue;
//                }
//                cornerType = CORNER_TYPES[i];
//                transformations.add(new RoundedCornersTransformation((int) view.borderCornerRadii[i], 0,
//                        cornerType));
//            }
//            multi = new MultiTransformation(transformations);
//            options = options.apply(bitmapTransform(multi));
//
//        }

        requestManager
                .load(view.glideUrl.toStringUrl())
                .thumbnail(requestManager.load(view.defaultSource))
                .apply(options)
                .listener(LISTENER)
                .into(view);
    }


my glide version 4.40 , jp.wasabeef 3.1
if i use Transformation Memory will overflow

**Comment by chaitanya0bhagvan** [comment]
@fangasvsass This library still uses glide 3. Since you are using glide 4 and this memory issue does look like a glide related you may get better support from glide team.

**Comment by baona95** [comment]
I am using react native navigation also so this is a concern.

**Comment by DylanVann** [comment]
@chaitanya0bhagvan I think some of this was referenced for another PR that was merged to fix memory leaks. For the `borderRadius` the wrapping view approach seems to have worked well, it's cross platform and consistent with the rest of React Native, they've also fixed the bugs with it.

Thank you for the work, I'll credit you in the release notes!

**Pull request closed without merging**
