### PR TITLE
React 18.0.0 support

### PR DESCRIPTION
**Pull request by aplimrek**
**Changes :** 

- React 18.0.0 support added

### CODE REVIEW

**Comment by KilianB** [comment]
This will drop support for react 17 which surely is not intended.
Did you check any regression which may happen due to upgrading to react 18?

**Comment by evgeniy-skakun** [comment]
"react": "^16.8.6 || ^17.0.0 || ^18.0.0" ?

 @KilianB @aplimrek

**Comment by nibblesnbits** [comment]
Any movement on this?  I hope to be able to upgrade soon.

**Comment by DylanVann** [comment]
I'm going to go with `^17 || ^18`. Seems it might have some regressions, to be resolved in patch releases.

**Pull request closed without merging**
