### PR TITLE
Memory Leak on iOS: FastImage not released from memory when callbacks onLoad is set

### PR DESCRIPTION
**Pull request by StevenMasini**
# Changelog

Solution to the open issue #371

- Use a `weak` reference to `self` to call `sendOnLoad` in the `sd_setImageWithPreviousCachedImageWithURL:placeholderImage:options:progress:completed:`

Holding a `strong` reference to `self` in a block can lead to memory leaks as the block will hold the reference until it is called.

[Always pass weak reference of self into block in ARC?](https://stackoverflow.com/a/20032131)

### CODE REVIEW

**Comment by adammcarth** [comment]
I seem to be getting two compile errors in XCode when running these changes:

1) `Implicit conversion of an Objective-C pointer to 'FFFastImageView *const __weak *' is disallowed with ARC`.
```objectivec
__weak typeof(self) *weakSelf = self;
```

2) `Bad receiver type 'FFFastImageView *const __weak *'`.
```objectivec
[weakSelf sendOnLoad:image];
```

**Comment by StevenMasini** [comment]
@adammcarth Okay I will have a look at it. Sound weird tho, you are not supposed to pass a strong pointer into a block.

**Comment by marf** [comment]
> I seem to be getting two compile errors in XCode when running these changes:
> 
> 1. `Implicit conversion of an Objective-C pointer to 'FFFastImageView *const __weak *' is disallowed with ARC`.
> 
> ```objc
> __weak typeof(self) *weakSelf = self;
> ```
> 
> 1. `Bad receiver type 'FFFastImageView *const __weak *'`.
> 
> ```objc
> [weakSelf sendOnLoad:image];
> ```

Hello @adammcarth I have the same problem trying to applying the fix.
What should we do?

Thank you,
Marco

**Comment by StevenMasini** [comment]
Yeah sorry guys my bad, the correct syntax is `__weak typeof(self) weakSelf = self;`. It's been a while since I wrote Objective C, I forgot that `typeof(self)` will already define the type as a pointer.

**Comment by StevenMasini** [comment]
Well okay I am stupid, I have been chasing a ghost 😓 

Actually if you implement `onLoadStart `, `onError` or `onLoadEnd` and you try to retrieve a parameter from it. Then you will end up with a huge memory leak.

I was trying to retrieve `error` from `onError`, but actually the native part doesn't return it at all.

Well at least I have discovered that you can't retrieve a parameter that doesn't exist from a callback.

Anyway we still need to give a weak pointer of self to the completion block of SDWebImage.

**Comment by marf** [comment]
Hello, @StevenMasini and thank you.
So has this fix fixed the memory leaks?

Also changing from RTCBubblingEventBlock to RTCDirectEventBlock fixes the fact of the parameters to the callback which may generate memory leaks?

Thank you,
MArco

**Comment by StevenMasini** [comment]
I am preparing another Pull Request with more fixes. I am closing this Pull Request as the new Pull Request will contain these fix and more.

**Pull request closed without merging**
