### PR TITLE
Cross-platform tint color support

### PR DESCRIPTION
**Pull request by emilyjbeckers**
I needed this for a project that I was working on and it will also resolve this issue https://github.com/DylanVann/react-native-fast-image/issues/124

### CODE REVIEW

**Comment by emilyjbeckers** [comment]
Merged master and now passes CI

**Comment by emilyjbeckers** [comment]
@DylanVann have you had a chance to give this a look to merge it in? I don't want to have to keep doing merges 😅

**Comment by shwetsolanki** [comment]
@DylanVann Any plans to merge this? We also need this functionality

**Comment by VinceBT** [comment]
@DylanVann Can you merge this ?

**Comment by WFolini** [comment]
@DylanVann Any news about this?

**Comment by Brianvdb** [comment]
@DylanVann Any news?

**Comment by barghi** [comment]
Hey guys do you have any plane to merge this ?

**Comment by barghi** [comment]
Hey guys do you have any plan to merge this ?

**Comment by stokesbga** [comment]
Note* the tintColor being set to something, and then moving to null does not work on iOS, will push changes shortly

**Comment by stokesbga** [comment]
on iOS, resetting tintColor to null does not work, and instead persists the previously set tintColor.

**Comment by stokesbga** [comment]
if you add 
```
- (void)setImageColor:(UIColor *)imageColor {
    if (imageColor != nil) {
        _imageColor = imageColor;
        super.image = [self makeImage:super.image withTint:self.imageColor];
    } else {
        super.image = _imageBackup;
    }
}

- (void)setImage:(UIImage *)image {
    if (self.imageColor != nil) {
        super.image = [self makeImage:image withTint:self.imageColor];
    } else {
        _imageBackup = image;
        super.image = image;
    }
}
```

then it works, but I dont like the idea of storing two copies...

**Comment by OlivierFreyssinet** [comment]
Is this gonna be merged soon ? Really need this 😁

**Comment by ericvicenti** [comment]
One day this will be merged and I will be able to migrate away from this: https://www.npmjs.com/package/react-native-fast-image-with-tint-color

**Comment by DimitryDushkin** [comment]
@DylanVann please?)

**Comment by Fabian-Fynn** [comment]
@DylanVann can we please merge this?

**Comment by Maddoc42** [comment]
Second that 👍 

If a merge is not possible, @emilyjbeckers any chances we can hope for an updated version of your fork? v5.3.0 was recently released which addresses some memory issues on iOS (#433) 😇

**Comment by DylanVann** [comment]
I third that. @DylanVann please!

**Comment by DylanVann** [comment]
@emilyjbeckers, sorry it took so long, thank you!

**Comment by DylanVann** [comment]
@ericvicenti If this was made into a style prop we'd be forced to call https://facebook.github.io/react-native/docs/stylesheet#flatten on each render right? Wouldn't that be worse for performance, or is there another way you know of working it out?

**Comment by chrisfahy** [comment]
if this library could be maintained it would help my project considerably. i am a noob so cant help. only been programming 6 mths. but please know ppl use it and it was working amazingly

**Comment by DylanVann** [comment]
@chrisfahy This feature has been merged and released, check the releases page.

**Comment by chrisfahy** [comment]
i am having issues with memory pressure and am thinking its with fast image. any ideas for me? or can you recommend another library like this one? cheers for your time

**Comment by DylanVann** [comment]
You could try upgrading, a memory leak was fixed recently. Alternatively:

- Open a new issue with more information. 
- Resize your images server side if they're too big.
- Use `Image`.
- Use native image loading libraries directly.

**Comment by chrisfahy** [comment]
Thank you @DylanVann. will try that this morning. i appreciate the help.

**Pull request merged**
