### PR TITLE
Update SDWebImage version to 4.4.3

### LINKED ISSUE #298: WebP not showing on iOS 12
"react": "16.5.0",
"react-native": "0.57.1",
"react-native-fast-image": "^5.0.10"

### PR DESCRIPTION
**Pull request by ds8k**
This updates the version of SDWebImage to 4.4.3, which has fixes for webp images rendering in iOS 12. This fixes #298 #385

### CODE REVIEW

**Comment by jjgp** [comment]
I will preface this with I could have messed up a step. I made my fork and merged these changes in here: https://github.com/jjgp/react-native-fast-image

Then I did the following to integrate: 
```
$ yarn add https://github.com/jjgp/react-native-fast-image/tarball/master 
$ react-native link react-native-fast-image
```

And upon building I am seeing:
screen shot 2019-01-10 at 2 23 04 pm

Just wanted to try out these changes. I appreciate the update!

**Comment by jjgp** [comment]
I'm definitely going to chalk it up as I didn't do integrate it correctly. I was curious how you linked it up to test it?

**Comment by ds8k** [comment]
@jjgp I actually haven't tested it. I could not get it installed and linked properly due to the submodule not initializing correctly

**Comment by jjgp** [comment]
I'll look into it more too. Maybe @DylanVann would have some insight too 👍

**Comment by Almouro** [comment]
Hello,

I successfully tested that PR and it fixes the issue of ios12 webp images not being displayed.

To test I did:

```shell
cd node_modules
rm -rf react-native-fast-image
git clone ds8k/react-native-fast-image
cd react-native-fast-image
git submodule update --init --recursive
```

This also seemed to annoy XCode so I did the usual clean/quit XCode/remove `DerivedData` folder before rebuilding.

@DylanVann any chance we can get this in? :)

@ds8k note that your commit isn't linked to your GitHub profile (your profile picture doesn't appear). In case that's not intended, you should be able to fix it by setting your email in your local git config with `git config --global user.email email@example.com` 😉

**Comment by ds8k** [comment]
@Almouro That's awesome! Thanks for testing it out

**Comment by ds8k** [comment]
@DylanVann Could this get looked at soon?

**Comment by mushinz** [comment]
This is a must have PR. @DylanVann can you please take a look how to get this update of SDWebImage into play?


Regards

**Comment by introin** [comment]
+1 Please

**Comment by Almouro** [comment]
In case that can help you guys in the meantime, in our project, we decided to remove the `Vendors` and install `SDWebImage` as pod, making it way easier to manage `SDWebImage` dependencies.

To remove the `Vendors` folder we created a patch with `https://github.com/ds300/patch-package` 

## Podfile
```ruby
target 'YOUR_TARGET' do
  ...
  pod 'SDWebImage', '= 4.4.3'
  pod 'SDWebImage/GIF', '= 4.4.3'
  pod 'SDWebImage/WebP', '= 4.4.3'
end
```

**Comment by tjbenton** [comment]
When is this PR going to get merged? I really need this update for my current project

**Comment by DylanVann** [comment]
Thank you @ds8k !

https://github.com/DylanVann/react-native-fast-image/releases/tag/v5.1.2

**Pull request merged**
