### PR TITLE
support border raduis for android

### PR DESCRIPTION
**Pull request by yiky84119**

### CODE REVIEW

**Comment by omeraplak** [comment]
@DylanVann 

Image of Yaktocat

**Comment by foggy1** [comment]
Might be missing something but if I try to manually implement these changes I can't a truly round image, the corners just get weirdly clipped.

**Comment by omeraplak** [comment]
@foggy1  yes true but it's working different size.
Example, 60x60 (round: w-h half = 30) image can not round but 62, 62 (32) it's working. i don't understand but i need this. I changed my picture sizes on my application and use the temp solution.

**Comment by yiky84119** [comment]
i just test 60*60 radius 30, it works fine,could you show me how to reproduce the bug?

**Comment by omeraplak** [comment]
@yiky84119 Yes i can give more information few hours later. Maybe you just test on ios? Did you test on Android?

**Comment by omeraplak** [comment]
@yiky84119 
Usage
`<FastImage
			style={profilePhoto}
			source={{ uri: imageUrl }}
		/>
`

my image style,
`profilePhoto: {
	borderRadius: 30,
	height: 60,
	width: 60
} as ImageStyle,
`

**Comment by yiky84119** [comment]
I have fix it, you can try again later.
npm install react-native-fast-image-nevo

**Comment by omeraplak** [comment]
@yiky84119 i checked and it's fixed. Thank you!

**Comment by dotansimha** [comment]
@yiky84119 
Trying to use your latest version of the fork.

Android seems a bit buggy, and the radius is incorrect.

using: `style={{ width: 80, height: 80 }}` and `borderRadius={40}`, in iOS the Image seems as circle, but in Android it seems like an ellipse and not as perfect circle.

Any idea why? @yiky84119

**Comment by guoliang1206** [comment]
Does any new things about this issue?

**Comment by wkoutre** [comment]
@guoliang1206 @dotansimha 

My workaround for this is as follows:

```
const IMAGE = IOS ? (
      <FastImage
        resizeMode={FastImage.resizeMode.cover}
        source={picObj}
        style={Styles.profilePicStyle}
      />
    ) : (
      <View style={Styles.profilePicStyle}>
        <Image
          source={picObj}
          resizeMode={"cover"}
          style={[Styles.flex1, Styles.androidProfilePic]}
        />
      </View>
    );
```

The styles are just `width`, `height`, and `borderRadius`.

**Comment by yiky84119** [comment]
sorry guys, only support square picture now, i will fix later

**Comment by DylanVann** [comment]
Thanks for all the help looking into this, sorry for the wait.

I think the wrapping view approach is probably the best because it:

- Works on iOS and Android.
- Doesn't cause any issues in common scenarios.
- Will support other types of border radius when they are fixed in RN core on android.
  - `borderTopLeftRadius`
  - `borderTopRightRadius`
  - `borderBottomLeftRadius`
  - `borderBottomRightRadius`
  - etc.
- Currently these other types work on iOS but the android view masking code doesn't handle them. I'm thinking about taking a shot at fixing it.

screen shot 2018-01-30 at 20 43 02

A new version has been released that you can try out now.

**Comment by brunolemos** [comment]
> I think the wrapping view approach is probably the best 

@DylanVann I had border radius working on android before migrating to FastImage. If you are talking about the comment above yours, it's basically using normal Image when it's android, which I don't consider a solution.

**Comment by DylanVann** [comment]
@brunolemos That's the solution being used in the image above. I think it does work, maybe you were trying before they implemented the masking on android.

**Comment by brunolemos** [comment]
Upgrading react native made the masking work on Android.

**Comment by ezha86** [comment]
can anyone confirm that border radius does work on android ?
for me seems it doesnt
"react-native": "^0.53.0",
"react-native-fast-image": "^2.2.5",

**Comment by CristiTr** [comment]
same here, not working on android device:

"react-native": "^0.53.3",
 "react-native-fast-image": "^2.2.5",

**Comment by ezha86** [comment]
i ended this by wrapping fast-image within view:
<View style={styles.avatarRadius}>
       <FastImage
                    style={styles.avatar}
                    source={{
                      uri: {uri},
                      priority: FastImage.priority.normal,
                    }}
       />
</View>

avatarRadius:{
    borderRadius: 25,
    width: 50,
    height: 50,
    overflow: 'hidden',
  },
  avatar: {
    flex: 1,
  },

**Comment by DylanVann** [comment]
@ezha86 @CristiTr The current version of `react-native-fast-image` is `v.4.0.8`. It will work if you upgrade.

**Pull request closed without merging**
