### PR TITLE
Bump SDWebImageWebPCoder version to 0.6.1

### PR DESCRIPTION
**Pull request by radko93**
This enabled multi-thread encoding for improved performance. Also, SDWebImage 5.7 seems to be required https://github.com/SDWebImage/SDWebImageWebPCoder/pull/35 so I'm bumping it also to enforce it for people that are upgrading.

### CODE REVIEW

**Comment by chuganzy** [comment]
Any plan to merge this?

**Comment by jenshandersson** [comment]
Isn't it better to allow minor changes instead?
`s.dependency 'SDWebImageWebPCoder', '~> 0.6'`

**Comment by radko93** [comment]
@jenshandersson, you're right. I changed this now.

**Comment by DylanVann** [comment]
This was done in another PR. Thank you though!

**Pull request closed without merging**
