### PR TITLE
iOS: Ensure onLoad and onLoadEnd get called

### PR DESCRIPTION
**Pull request by danhodos**
Setting properties from JS to native components does not guarantee any
order (as far as I know). Because of this, `setSource` can get called
and complete before `setOnFastImageLoad` and `setOnFastImageLoadEnd`,
which results in the callbacks never firing.

This change implements a simple check for these callback properties
getting set after the image has loaded, and fires them at that time.

### CODE REVIEW

**Comment by danhodos** [comment]
This might possibly fix #37.

**Comment by dotansimha** [comment]
@DylanVann @danhodos 
Confirm that it solved issue with `react-native-image-progress`.

**Comment by ovaris** [comment]
Please merge!

**Comment by ovaris** [comment]
@DylanVann Any news on this, we really need onLoadEnd to be called also for cached imgs?

**Comment by ovaris** [comment]
@danhodos I'm not able to build this on xcode (9.1):
```
node_modules/react-native-fast-image/ios/FastImage/FFFastImageView.h:3:9: fatal error: 'SDWebImage/UIImageView+WebCache.h' file not found
#import <SDWebImage/UIImageView+WebCache.h>
```

**Comment by shinyford** [comment]
Hi @DylanVann - I'm having problems with callbacks not firing on iOS (works fine on Android) and it looks like this may fix it. Any chance that it could be merged in? Or are there other issues?

**Comment by brunolemos** [comment]
@shinyford while it is not merged, you can apply it using [patch-package](https://github.com/ds300/patch-package)

**Comment by patrickkempff** [comment]
@DylanVann it would be really nice to have this merged

**Comment by varungupta85** [comment]
Verified that the fix worked for me.

**Comment by DylanVann** [comment]
@danhodos Thank you for fixing this 😃 

Works great. I added an example of usage with `react-native-image-progress` as well.

progress

All these properties are really tied together, I've considered just setting everything in one object:

```jsx
<Image source={{ uri: 'www.dfsfd.com/thing.png', onLoadEnd: () => console.log('loaded') }} />
```

That could potentially solve all these issues. It's sort of a weird API though, and it would break compatibility with `react-native`'s `Image`.

**Comment by DylanVann** [comment]
Sorry I messed up a rebase here. The actual commit is: https://github.com/DylanVann/react-native-fast-image/commit/d9f729915486665d9aad1f1febff5348ab3ab069

**Pull request merged**
