### PR TITLE
Feat/progress.

### PR DESCRIPTION
**Pull request by DylanVann**

### CODE REVIEW

**Comment by DylanVann** [comment]
Need to pull in something like [this](https://gist.github.com/TWiStErRob/08d5807e396740e52c90) for android.

**Comment by bang88** [comment]
Thats awesome.  waiting the new features. 😄

**Comment by TsuryKnox** [comment]
Any progress with this PR? I've upgraded to the latest RN version and now I can't use FastImage...

**Comment by DylanVann** [comment]
I think this should be working properly now. Just need to test it out a bit more.

**Pull request merged**
