### PR TITLE
Add onProgress and onComplete to preload.

### PR DESCRIPTION
**Pull request by doomsower**
The title is pretty self-descriptive. Here is the feature request topic: #144

Hopefully will add Android counterpart on Saturday.

### CODE REVIEW

**Comment by retyui** [comment]
https://github.com/DylanVann/react-native-fast-image/issues/266

**Comment by doomsower** [comment]
> #266

This can be easily added on JS side (e.g. when onProgress and onComplete are both undefined, make JS method return promise). 
But first I want maintaineer to review this PR at least. Btw I already use this code in a small production app, no complaints and crashes so far.

**Comment by retyui** [comment]
@doomsower :+1:

**Comment by aaalive** [comment]
Hi 
It's very useful, could you please merge?

**Comment by alirezarastegarfard** [comment]
how can i use this feature ?

**Comment by elan** [comment]
Any plans on getting this merged? Would be awesome to not have to fork the repo to use it 😅

**Comment by ChristianTucker** [comment]
Please get this merged. 

@retyui  @DylanVann

**Comment by luco** [comment]
@DylanVann Merge this please.

**Comment by IljaDaderko** [comment]
Is there anything preventing this PR from being merged? Would love to help :)

**Comment by retyui** [comment]
@DylanVann ^

**Comment by francisdelgad** [comment]
@DylanVann willing to resolve CI failure to get this merged into the package. Some guidance would be appreciated though.

**Comment by DylanVann** [comment]
Sorry for the lack of response. The reason I did not implement this feature, and the reason I'd be hesitant to merge this is that the API SDWebImage provides for prefetching images is not very good.

It does not tell you which images fail and succeed, it only gives you the number of successful loads and failed loads, which seems silly to me.

If someone did a PR to improve their API I'd be much more likely to merge something like this.

**Comment by francisdelgad** [comment]
> Sorry for the lack of response. The reason I did not implement this feature, and the reason I'd be hesitant to merge this is that the API SDWebImage provides for prefetching images is not very good.
> 
> It does not tell you which images fail and succeed, it only gives you the number of successful loads and failed loads, which seems silly to me.
> 
> If someone did a PR to improve their API I'd be much more likely to merge something like this.

Awesome, I was wondering why it hadn't been merged; seems like a good feature. But that is a valid reason not to merge this feature.

**Comment by doomsower** [comment]
@DylanVann and everyone interested

I've this PR. Now iOS progress handler checks if the url it receives is cached on disk. Based on this JS callbacks will now return array of cached urls as first argument.

I also merged master, so it's up to date with v7 of this module, and I updated example project to RN 0.60.5. Example project works fine on iOS and Android. However, I haven't tried this in a real project, as I have yet to migrate my app that utilizes preloading to RN 0.60

**Comment by DylanVann** [comment]
Closing this until we can resolve the blocking issue of SDWebImage not giving enough info.

I wrote a `roadmap.md` file to keep track of this kind of thing, with a link to this PR.

https://github.com/DylanVann/react-native-fast-image/blob/master/docs/roadmap.md#add-onprogress-and-oncomplete-to-preload

**Pull request closed without merging**
