### PR TITLE
Added tvOS target

### PR DESCRIPTION
**Pull request by psegalen**
Hi, this is an attempt to add tvOS target to this lib, this is related to #162 
I'm not able to build the tvOS lib because it doesn't reference React Native (so it doesn't find "React/RCTConvert.h") but given the fact that it doesn't find it either when I try to build the iOS lib, I figured I missed something, could you please point me in the right direction to build it?
Thanks.

### CODE REVIEW

**Comment by DylanVann** [comment]
Cool, thanks for working on this.

There's another PR open that changes that RCTConvert import, it might fix it.

**Comment by psegalen** [comment]
I tried everything the other PR tried but XCode still won't find the header file... :'(
Maybe it has something to do with my machine, could someone please try and compile the tvOS target on his machine?

**Comment by DylanVann** [comment]
Harder than it looks...

**Comment by nic-thomson** [comment]
Had a look at this thru brute force; I was able to get this to compile.  The secret is to add 
$(inherited) 
to the header search paths. Then drag that item to the top of the list.

**Comment by gtebbutt** [comment]
Just come across this - was there any major blocker to getting it working based on @nic-thomson's suggestion? Would be very useful to have, but seems to have gone somewhat out of sync now.,

**Comment by Ilphrin** [comment]
Hi @psegalen ! Any news on this PR? :3

**Comment by iamyellow** [comment]
hi! i've made a new PR (https://github.com/DylanVann/react-native-fast-image/pull/486) since it seems this one have problems merging.

**Comment by DylanVann** [comment]
Closed in favor of @iamyellow 's PR,

**Pull request closed without merging**
