### PR TITLE
Update Readme for RN 0.59.x or lower

### PR DESCRIPTION
**Pull request by yogeshkotadiya**
Added Installation steps for adding RN-fast-image on RN version 0.59.x or lower

### CODE REVIEW

**Comment by DylanVann** [comment]
I don't think the benefits of backwards compatibility / documenting backwards compatibility are worth the cost given the pace of React Native development changing. Sorry if it's inconvenient.

**Comment by WeslleyNasRocha** [comment]
I find this pretty valid, i use this on my company app, and it cant keep the pace of the react-native updates, we currently updated from 0.54 to the 0.59 and not planning update to the 0.60 until its matured.

**Comment by WeslleyNasRocha** [comment]
Actually, a lot of libraries do this.

**Comment by Kris-Lee-SH** [comment]
So, version 6.1.1 is for RN 0.59?

**Comment by cupcakearmy** [comment]
As a single maintainer I totally understand that the cost of making it backwards compatible are not feasible. BUT just a hint to wich version was "last seen working with 0.59 .e.g" would be very useful.
As a company you don't always have the luxury of upgrading to every latest version when you have tons of native dependencies.

Seems like 6.1.1 for 0.59

Thanks for the library though! ❤️

**Comment by xclidongbo** [comment]
ThankX

**Pull request closed without merging**
