### PR TITLE
Migrating to AndroidX

### PR DESCRIPTION
**Pull request by vokhuyetOz**

### CODE REVIEW

**Comment by WrathChaos** [comment]
Waiting for this PR...

**Comment by mkamals** [comment]
Kindly merge this PR soon and release a new version of the package. This is creating lot of issues with the build generation in Android.

**Comment by arunalt** [comment]
Hey @DylanVann,

Do we have any ETA on when this PR will get merged? We're looking to migrate to AndroidX and this is a huge dependency for us. Would really appreciate a response! 

Cheers. 
Arun.

**Comment by rborn** [comment]
@DylanVann I can confirm the PR works well (I'm using it now as replacement for this one till it gets merged) 
@vokhuyetOz  maybe you could rebase so the PR can be merged when the time comes ? ❤️

**Comment by die20** [comment]
For some reason when I try to fork this branch and try to use it in an application, I get this when I run `yarn install`:
```
fatal: not a git repository (or any of the parent directories): .git
error Command failed with exit code 128.
```

This is how I'm trying to use it on the package.json:
```
"react-native-fast-image": "git+https://github.com/vokhuyetOz/react-native-fast-image",
```

**Comment by rborn** [comment]
@die20 
`"react-native-fast-image": "git+https://github.com/vokhuyetOz/react-native-fast-image.git",`

you forgot the trailing `.git` 😊

**Comment by JimtotheB** [comment]
@rborn The trailing .git doesn't matter, I can reproduce this behavior in a bare project, It also produced the same error with `yarn add https://github.com/DylanVann/react-native-fast-image` which is 100% the correct way to add a git repo via yarn 😊

**Comment by rborn** [comment]
@JimtotheB this works for me, however it takes 1000 years to finish 😔

`npm install -ddd  https://github.com/DylanVann/react-native-fast-image.git`

**Comment by JimtotheB** [comment]
@rborn, I think this is specific to yarn, I'm sure npm is unpacking the submodule correctly and yarn is not.

**Comment by die20** [comment]
@rborn It seems to be a yarn issue. It's not just this branch though, it's the master of `react-native-fast-image`. 

I was able to get it installed with npm but remote gifs appear to not be working with this commit. The gif does not play.

**Comment by Ilphrin** [comment]
There will be a need for an approval now that RN 60 is out, it needs AndroidX support for all libraries so until this PR is merged, react-native-fast-image may not work anymore on Android for 0.60 :/ We do not use this version yet so can't test yet though...

**Comment by DylanVann** [comment]
I have tried this PR, it does work with the new RN version by default.

The one thing blocking me from merging is that the example application includes other 3rd party libraries that do not support AndroidX.

**Comment by vokhuyetOz** [comment]
@DylanVann i saw react-native-gesture-handle don't migrate to androidX, it causes the error

**Comment by vokhuyetOz** [comment]
should we wait for it ?

**Comment by DylanVann** [comment]
I used `jetify` to fix the examples. This is great, thanks @vokhuyetOz! I ended up merging from another branch.

**Comment by mkamals** [comment]
Thanks @DylanVann for merging this PR.

**Pull request closed without merging**
