### PR TITLE
reapplied clear image cache PR

### PR DESCRIPTION
**Pull request by trickeyd**
Just reapplied this PR to latest version

https://github.com/DylanVann/react-native-fast-image/pull/425#issuecomment-906271383

### CODE REVIEW

**Comment by sharan-SKY** [comment]
Can we get this merged as its a very crucial feature. :)

**Review by sharan-SKY — APPROVED** [review]

**Comment by alburdette619** [comment]
@trickeyd I made a fork & pulled in this PR and switched off `webp` format as suggested by #46 but still get memory issues & a crash on iOS after 300-500 images.

**Comment by DylanVann** [comment]
LGTM! 🚢

**Comment by trickeyd** [comment]
Thanks for merging the original. I'll close this one.

**Pull request closed without merging**
