### PR TITLE
Allow FastImageView component to be the target of the forwardRef

### PR DESCRIPTION
**Pull request by grean**
So, FastImage component can be join by ref in users code.

### CODE REVIEW

**Comment by todorone** [comment]
LGTM
@DylanVann Can we merge this?

**Comment by DylanVann** [comment]
What does this allow that the current ref does not? I would think having the outermost view would be most useful.

**Comment by DylanVann** [comment]
If you still think this is a good change please open another PR with a description of why the ref change is useful. Thank you!

**Comment by maksimgorodilov** [comment]
Hello @DylanVann this PR can help us to programatically change source uri of the image (for example updating it on scroll) with `setNativeProps`

**Pull request closed without merging**
