### PR TITLE
Update react-native to 0.61.1

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates `react-native` in the example project to `0.61.1` (including several other dependency updates). The project is now fully lint-free (standard react-native eslint/prettier applied in a separate commit.

Successfully verified and tested on:
- Android Device (Xiaomi Mi A2)
- Android Emulator (Pixel 3a)
- iOS Device (iPhone 8)
- iOS Simulator (iPhone X)

<sub><sup>Once approved, please use a *normal* GitHub merge (i.e. **NO rebase/squash** merge) to integrate the commit(s) from the PR head branch. The changes are broken up into meaningful, [atomic commits](https://www.freshconsulting.com/atomic-commits/), and my branch should already be up-to-date with the latest base branch. If it isn't, or if you want me to change anything, please let me know, and I will update the branch as soon as possible. Thank you!</sup></sub>

### CODE REVIEW

**Comment by friederbluemle** [comment]
Updated to `0.61.1`

**Comment by friederbluemle** [comment]
Rebased onto latest `master` branch.

**Comment by DylanVann** [comment]
@friederbluemle Sorry I didn't get to this. I've updated things on main.

**Comment by friederbluemle** [comment]
No worries, thanks for all your hard work @DylanVann :+1:

**Pull request closed without merging**
