### PR TITLE
better Quality Decoding for Android

### PR DESCRIPTION
**Pull request by TilWs**
set the DecodeFormat of the GlideBuilder to better quality, which fixes banding.

### CODE REVIEW

**Comment by MariusMeiners** [comment]
could you maybe merge this in ? @DylanVann

**Comment by MariusMeiners** [comment]
this should solve issue #161

**Comment by fangasvsass** [comment]
only update glide to 4.x this issue Can solve

**Comment by DylanVann** [comment]
@MariusMeiners 

Thanks for the PR! Glide 4 update is held up by an issue I'm not sure how to solve, so we can try this out to solve banding. Thank you

**Pull request merged**
